/**
 * build-memory.ts — Builds project memory from the repo scan index.
 *
 * Usage: npx tsx .magneto/scripts/build-memory.ts
 *
 * Reads: .magneto/cache/repo-index.json
 * Outputs: .magneto/memory/root-summary.md (updated)
 */

import * as fs from 'fs';
import * as path from 'path';

const PROJECT_ROOT = path.resolve(__dirname, '../..');
const indexPath = path.join(PROJECT_ROOT, '.magneto', 'cache', 'repo-index.json');

if (!fs.existsSync(indexPath)) {
  console.error('No repo index found. Run scan-repo.ts first.');
  process.exit(1);
}

const index = JSON.parse(fs.readFileSync(indexPath, 'utf-8'));
const files: { path: string; extension: string }[] = index.files;

// Group by extension
const byExtension: Record<string, number> = {};
for (const f of files) {
  byExtension[f.extension] = (byExtension[f.extension] || 0) + 1;
}

// Group by top-level directory
const byDir: Record<string, number> = {};
for (const f of files) {
  const topDir = f.path.split('/')[0] || f.path.split(path.sep)[0];
  byDir[topDir] = (byDir[topDir] || 0) + 1;
}

const summary = `# Project Memory — Root Summary

## Overview
Auto-generated by Magneto AI memory builder.

## Project Structure
Total files: ${files.length}

### By Extension
${Object.entries(byExtension).sort((a, b) => b[1] - a[1]).map(([ext, count]) => `- ${ext || '(none)'}: ${count}`).join('\n')}

### By Directory
${Object.entries(byDir).sort((a, b) => b[1] - a[1]).map(([dir, count]) => `- ${dir}: ${count}`).join('\n')}

## Last Updated
${new Date().toISOString()}
`;

const outPath = path.join(PROJECT_ROOT, '.magneto', 'memory', 'root-summary.md');
fs.writeFileSync(outPath, summary);
console.log('Memory updated → .magneto/memory/root-summary.md');
