import * as path from 'path';
import * as fs from 'fs';
import { logger } from '../utils/logger';
import { resolveProjectRoot, isMagnetoProject, magnetoPath } from '../utils/paths';
import { fileExists, writeText } from '../utils/fs';
import { buildContext, TaskInput } from '../core/context';
import { evaluateSecurity } from '../core/security-engine';
import { parseTaskFile } from '../utils/task-parser';

export interface GenerateOptions {
  output?: string;
  clipboard?: boolean;
  role?: string;
}

export async function generateCommand(taskFile: string, options: GenerateOptions): Promise<void> {
  const projectRoot = resolveProjectRoot();

  if (!isMagnetoProject(projectRoot)) {
    logger.error('Not a Magneto AI project. Run "magneto init" first.');
    process.exit(1);
  }

  const taskPath = path.resolve(projectRoot, taskFile);
  logger.info(`Generating prompt for: ${taskPath}`);

  let task: TaskInput;
  try {
    task = parseTaskFile(taskPath);
  } catch {
    logger.error(`Could not read task file: ${taskPath}`);
    process.exit(1);
  }

  // Build context
  const context = await buildContext(projectRoot, task);
  const security = evaluateSecurity(task, context);

  // Load role packs if available
  const rolePacks = loadRolePacks(projectRoot, context.roles);

  // Load relevant file contents
  const fileContents = loadScopedFiles(projectRoot, task.scope || []);

  // Load memory context if available
  const memory = loadMemoryContext(projectRoot);

  // Build the prompt
  const role = options.role || 'all';
  const prompt = buildPrompt(task, context, security, rolePacks, fileContents, memory, role);

  // Output
  const separator = '═'.repeat(70);
  if (options.output) {
    const outPath = path.resolve(projectRoot, options.output);
    writeText(outPath, prompt);
    logger.success(`Prompt saved to: ${outPath}`);
    logger.info(`${prompt.length} characters / ~${estimateTokens(prompt)} tokens`);
  } else {
    console.log('');
    console.log(separator);
    console.log('  MAGNETO AI — GENERATED PROMPT');
    console.log('  Copy and paste this into Windsurf / Copilot Chat');
    console.log(separator);
    console.log('');
    console.log(prompt);
    console.log('');
    console.log(separator);
    logger.info(`Prompt: ${prompt.length} characters / ~${estimateTokens(prompt)} tokens`);
    logger.info('Copy the prompt above and paste it into Windsurf or Copilot Chat.');
  }
}

function buildPrompt(
  task: TaskInput,
  context: any,
  security: any,
  rolePacks: Record<string, string>,
  fileContents: Record<string, string>,
  memory: string,
  role: string,
): string {
  const sections: string[] = [];

  // Header
  sections.push(`# Magneto AI Task: ${task.title}`);
  sections.push('');
  sections.push('> This prompt was generated by Magneto AI to give you scoped, structured context.');
  sections.push('> It contains only the files and constraints relevant to this task — saving tokens and improving quality.');
  sections.push('');

  // Task details
  sections.push('## Task');
  sections.push('');
  sections.push(`- **ID:** ${task.id}`);
  sections.push(`- **Title:** ${task.title}`);
  sections.push(`- **Type:** ${task.type}`);
  sections.push(`- **Classification:** ${context.classification}`);
  sections.push('');
  sections.push('### Description');
  sections.push('');
  sections.push(task.description);
  sections.push('');

  // Constraints
  if (task.constraints && task.constraints.length > 0) {
    sections.push('### Constraints (MUST follow)');
    sections.push('');
    for (const c of task.constraints) {
      sections.push(`- ${c}`);
    }
    sections.push('');
  }

  // Scope
  if (task.scope && task.scope.length > 0) {
    sections.push('### Scoped Files');
    sections.push('');
    sections.push('Only these files/directories are in scope for this task:');
    sections.push('');
    for (const s of task.scope) {
      sections.push(`- \`${s}\``);
    }
    sections.push('');
  }

  // Security
  sections.push('## Security Constraints');
  sections.push('');
  sections.push(`- **Risk Level:** ${security.securityRisk}`);
  sections.push(`- **Approval Required:** ${security.approvalRequired ? 'Yes' : 'No'}`);
  if (security.blockedActions.length > 0) {
    sections.push(`- **Blocked Actions:** ${security.blockedActions.join(', ')}`);
  }
  if (security.reasons.length > 0) {
    sections.push(`- **Security Notes:** ${security.reasons.join('; ')}`);
  }
  sections.push('');

  // Assigned roles
  sections.push('## Agent Roles');
  sections.push('');
  if (role === 'all') {
    sections.push('You are acting as **all Magneto AI agents** for this task. Consider each perspective:');
    sections.push('');
    for (const r of context.roles) {
      sections.push(`- **${r}** — ${getRoleDescription(r)}`);
    }
  } else {
    sections.push(`You are acting as the **${role}** agent. ${getRoleDescription(role)}`);
  }
  sections.push('');

  // Role pack instructions
  const activeRoles = role === 'all' ? context.roles : [role];
  for (const r of activeRoles) {
    if (rolePacks[r]) {
      sections.push(`### ${r.charAt(0).toUpperCase() + r.slice(1)} Instructions`);
      sections.push('');
      sections.push(rolePacks[r]);
      sections.push('');
    }
  }

  // Memory context
  if (memory) {
    sections.push('## Project Memory');
    sections.push('');
    sections.push('Previously captured project context (from `.magneto/memory/`):');
    sections.push('');
    sections.push(memory);
    sections.push('');
  }

  // File contents
  const fileKeys = Object.keys(fileContents);
  if (fileKeys.length > 0) {
    sections.push('## Relevant File Contents');
    sections.push('');
    sections.push(`*${fileKeys.length} files loaded into context. Files outside scope are excluded to save tokens.*`);
    sections.push('');
    for (const [filePath, content] of Object.entries(fileContents)) {
      const ext = path.extname(filePath).slice(1) || 'text';
      sections.push(`### \`${filePath}\``);
      sections.push('');
      sections.push('```' + ext);
      sections.push(content);
      sections.push('```');
      sections.push('');
    }
  }

  // Instructions
  sections.push('## What To Do');
  sections.push('');
  sections.push(getTaskInstructions(task.type, context.classification));
  sections.push('');

  // Output format
  sections.push('## Expected Output');
  sections.push('');
  sections.push('Please provide:');
  sections.push('');
  sections.push('1. **Code** — Complete, production-ready code for each file that needs changes');
  sections.push('2. **Explanation** — Brief explanation of what was changed and why');
  sections.push('3. **Tests** — Test cases covering the implementation (if applicable)');
  sections.push('4. **Risks** — Any risks or concerns with the implementation');
  sections.push('5. **Confidence** — Your confidence level (low/medium/high) in the solution');
  sections.push('');
  sections.push('For each code file, use this format:');
  sections.push('');
  sections.push('```');
  sections.push('// File: <path/to/file>');
  sections.push('<complete file contents>');
  sections.push('```');

  return sections.join('\n');
}

function loadRolePacks(projectRoot: string, roles: string[]): Record<string, string> {
  const packs: Record<string, string> = {};
  for (const role of roles) {
    const packPath = magnetoPath(projectRoot, 'roles', `${role}.pack.md`);
    if (fileExists(packPath)) {
      try {
        packs[role] = fs.readFileSync(packPath, 'utf-8').trim();
      } catch {
        // skip
      }
    }
  }
  return packs;
}

function loadScopedFiles(projectRoot: string, scope: string[]): Record<string, string> {
  const contents: Record<string, string> = {};
  const maxFileSize = 50000; // 50KB max per file
  const maxFiles = 20;
  let loaded = 0;

  for (const scopePath of scope) {
    if (loaded >= maxFiles) break;

    const fullPath = path.resolve(projectRoot, scopePath);

    if (!fs.existsSync(fullPath)) continue;

    const stat = fs.statSync(fullPath);
    if (stat.isFile()) {
      if (stat.size <= maxFileSize) {
        try {
          contents[scopePath] = fs.readFileSync(fullPath, 'utf-8');
          loaded++;
        } catch {
          // skip unreadable files
        }
      }
    } else if (stat.isDirectory()) {
      // Load files from directory (1 level deep)
      try {
        const files = fs.readdirSync(fullPath, { withFileTypes: true });
        for (const file of files) {
          if (loaded >= maxFiles) break;
          if (!file.isFile()) continue;

          const filePath = path.join(fullPath, file.name);
          const fileStat = fs.statSync(filePath);
          if (fileStat.size <= maxFileSize) {
            try {
              const relativePath = path.join(scopePath, file.name);
              contents[relativePath] = fs.readFileSync(filePath, 'utf-8');
              loaded++;
            } catch {
              // skip
            }
          }
        }
      } catch {
        // skip unreadable dirs
      }
    }
  }

  return contents;
}

function loadMemoryContext(projectRoot: string): string {
  const sections: string[] = [];

  // Root summary (from magneto analyze)
  const summaryPath = magnetoPath(projectRoot, 'memory', 'root-summary.md');
  if (fileExists(summaryPath)) {
    try {
      const content = fs.readFileSync(summaryPath, 'utf-8').trim();
      if (content.length > 200 && !content.includes('<!-- Auto-populated')) {
        sections.push(content);
      }
    } catch {
      // skip
    }
  }

  // Dependency map (from magneto analyze)
  const depsPath = magnetoPath(projectRoot, 'memory', 'dependencies.md');
  if (fileExists(depsPath)) {
    try {
      const content = fs.readFileSync(depsPath, 'utf-8').trim();
      if (content.length > 100) {
        sections.push(content);
      }
    } catch {
      // skip
    }
  }

  return sections.join('\n\n---\n\n');
}

function getRoleDescription(role: string): string {
  const descriptions: Record<string, string> = {
    orchestrator: 'Coordinate the task, decompose into subtasks, merge results, enforce security.',
    backend: 'Analyze and implement backend logic, APIs, data models, and architecture.',
    tester: 'Generate tests, validate coverage, identify edge cases and testing gaps.',
    requirements: 'Validate requirements traceability, detect spec-code contradictions.',
  };
  return descriptions[role] || 'Specialist agent.';
}

function getTaskInstructions(type: string, classification: string): string {
  const instructions: Record<string, string> = {
    'feature-implementation':
      'Implement the feature described above. Write complete, production-ready code for each file.\n' +
      'Follow all constraints. Include error handling, input validation, and type safety.\n' +
      'Generate corresponding test cases. Flag any requirements that are ambiguous.',
    'bug-fix':
      'Identify the root cause of the bug described above. Provide a fix with minimal changes.\n' +
      'Explain WHY the bug occurs, not just how to fix it.\n' +
      'Update or add tests that would catch this bug. Verify the fix doesn\'t break related functionality.',
    'security-audit':
      'Audit the scoped files for security vulnerabilities.\n' +
      'Check for: missing auth, injection vectors, sensitive data exposure, CORS issues, and OWASP Top 10.\n' +
      'For each finding, provide: severity, location, description, and recommended fix.',
    'performance-review':
      'Analyze the scoped files for performance issues.\n' +
      'Check for: N+1 queries, unnecessary re-renders, large bundle imports, missing caching.\n' +
      'For each finding, provide: impact level, location, and optimization recommendation.',
    'architecture-review':
      'Review the architecture of the scoped files.\n' +
      'Check for: pattern violations, tight coupling, missing abstractions, scalability concerns.\n' +
      'Propose incremental improvements — no big-bang rewrites.',
    'code-review':
      'Review the code for quality, consistency, and best practices.\n' +
      'Check for: code smells, naming issues, missing error handling, documentation gaps.\n' +
      'Provide actionable suggestions with code examples.',
    'testing':
      'Analyze test coverage for the scoped files.\n' +
      'Identify gaps: missing edge cases, untested error paths, stale tests.\n' +
      'Generate new test cases for uncovered scenarios.',
    'requirements-analysis':
      'Trace requirements to implementation in the scoped files.\n' +
      'Identify: unimplemented requirements, stale specs, contradictions between spec and code.\n' +
      'Provide a traceability matrix.',
    general:
      'Analyze the task and provide a comprehensive response.\n' +
      'Include code changes, tests, and risk assessment as applicable.',
  };
  return instructions[classification] || instructions[type] || instructions.general;
}

function estimateTokens(text: string): number {
  // Rough estimate: ~4 characters per token for English text/code
  return Math.ceil(text.length / 4);
}
