import * as path from 'path';
import * as fs from 'fs';
import { logger } from '../utils/logger';
import { resolveProjectRoot } from '../utils/paths';
import { readJson, writeJson, writeText, listFiles } from '../utils/fs';
import { mergeResults, MergedOutput } from '../core/merge-results';

export interface MergeOptions {
  format: 'json' | 'markdown';
}

export async function mergeCommand(outputDir: string, options: MergeOptions): Promise<void> {
  const projectRoot = resolveProjectRoot();
  const fullOutputDir = path.resolve(projectRoot, outputDir);

  if (!fs.existsSync(fullOutputDir)) {
    logger.error(`Output directory not found: ${fullOutputDir}`);
    process.exit(1);
  }

  logger.info(`Merging results from: ${fullOutputDir}`);

  // Collect all result JSON files
  const resultFiles = listFiles(fullOutputDir, /\.json$/);
  if (resultFiles.length === 0) {
    logger.warn('No JSON result files found in output directory.');
    return;
  }

  logger.info(`Found ${resultFiles.length} result file(s)`);

  const results: any[] = [];
  for (const file of resultFiles) {
    try {
      const data = readJson(path.join(fullOutputDir, file));
      results.push(data);
    } catch {
      logger.warn(`Skipping invalid file: ${file}`);
    }
  }

  const merged: MergedOutput = mergeResults(results);

  if (options.format === 'markdown') {
    const md = renderMarkdown(merged);
    const outPath = path.join(fullOutputDir, 'merged-report.md');
    writeText(outPath, md);
    logger.success(`Merged report saved: ${outPath}`);
  } else {
    const outPath = path.join(fullOutputDir, 'merged-report.json');
    writeJson(outPath, merged);
    logger.success(`Merged report saved: ${outPath}`);
  }
}

function renderMarkdown(merged: MergedOutput): string {
  const lines: string[] = [
    '# Magneto AI Merged Report',
    '',
    `**Task ID:** ${merged.taskId || 'N/A'}`,
    `**Confidence:** ${(merged.confidence * 100).toFixed(1)}%`,
    `**Risk Level:** ${merged.overallRisk}`,
    `**Agent Count:** ${merged.agentCount}`,
    '',
    '## Findings',
    '',
  ];

  for (const finding of merged.findings) {
    lines.push(`- **[${finding.source}]** ${finding.content}`);
  }

  lines.push('', '## Risks', '');
  for (const risk of merged.risks) {
    lines.push(`- ⚠ **${risk.severity}**: ${risk.description}`);
  }

  lines.push('', '---', `*Generated by Magneto at ${merged.mergedAt}*`);
  return lines.join('\n');
}
