/**
 * Cascade / Windsurf Runner
 * 
 * Handoff mechanism:
 * 1. Generates a scoped prompt from the task + context
 * 2. Writes it to .windsurf/workflows/ as an auto-executable workflow
 * 3. Also writes to .magneto/cache/prompt-{id}.md for direct Cascade reading
 * 4. Cascade auto-detects the prompt when the file opens in the IDE
 * 
 * The key insight: Cascade reads any file the user opens. By writing
 * the prompt to a well-known path and logging it, the agent picks it up.
 */

import * as fs from 'fs';
import * as path from 'path';
import { Runner, RunnerInput, RunnerOutput } from './types';
import { logger } from '../utils/logger';
import { getGlobalTokenCollector } from '../core/token-tracker';

export class CascadeRunner implements Runner {
  name = 'Cascade / Windsurf Runner';
  type = 'cascade' as const;

  async execute(input: RunnerInput): Promise<RunnerOutput> {
    logger.info('🌊 Executing task via Cascade (Windsurf) handoff...');

    const prompt = this.buildCascadePrompt(input);
    const taskId = (input.task.id as string) || 'task';

    // 1. Write prompt to .magneto/cache/ for direct reading
    const cachePath = path.join(input.projectRoot, '.magneto', 'cache', `prompt-${taskId}.md`);
    fs.mkdirSync(path.dirname(cachePath), { recursive: true });
    fs.writeFileSync(cachePath, prompt, 'utf-8');

    // 2. Write to .windsurf/workflows/ if .windsurf exists
    const windsurfDir = path.join(input.projectRoot, '.windsurf', 'workflows');
    const windsurfPath = path.join(windsurfDir, `magneto-${taskId}.md`);
    if (fs.existsSync(path.join(input.projectRoot, '.windsurf'))) {
      fs.mkdirSync(windsurfDir, { recursive: true });
      fs.writeFileSync(windsurfPath, this.buildWorkflow(input, prompt), 'utf-8');
      logger.success(`Windsurf workflow written: ${windsurfPath}`);
    }

    // 3. Log the prompt path so Cascade sees it in terminal output
    logger.success(`Cascade prompt ready: ${cachePath}`);
    logger.info('');
    logger.info('═══════════════════════════════════════════════════');
    logger.info('  MAGNETO → CASCADE HANDOFF');
    logger.info('═══════════════════════════════════════════════════');
    logger.info(`  Task: ${input.task.title || taskId}`);
    logger.info(`  Roles: ${input.context.roles.join(', ')}`);
    logger.info(`  Prompt: ${cachePath}`);
    logger.info('');
    logger.info('  Cascade will auto-read this prompt.');
    logger.info('  Open the file in Windsurf to trigger execution.');
    logger.info('═══════════════════════════════════════════════════');
    logger.info('');

    // Estimate token usage (Cascade doesn't provide actual usage)
    const promptTokens = Math.ceil(prompt.length / 4); // Rough estimate: ~4 chars per token
    const contextSize = input.context.relevantFiles.length;

    // Track token usage
    const collector = getGlobalTokenCollector(input.projectRoot);
    if (collector) {
      await collector.recordMetric({
        taskId: taskId,
        runner: 'cascade',
        model: 'cascade',
        withMagneto: true,
        inputTokens: promptTokens,
        outputTokens: 0, // Cascade handles output separately
        totalTokens: promptTokens,
        contextSize,
      });
    }

    return {
      success: true,
      findings: [
        {
          source: 'cascade',
          content: `Task prompt written to ${cachePath}. Cascade will auto-read and execute.`,
          confidence: 0.9,
        },
      ],
      risks: [],
      rawOutput: prompt,
      promptPath: cachePath,
      metadata: {
        runner: 'cascade',
        mode: input.mode,
        promptPath: cachePath,
        workflowPath: windsurfPath,
        handedOff: true,
        tokensUsed: promptTokens,
      },
    };
  }

  private buildCascadePrompt(input: RunnerInput): string {
    const task = input.task;
    const roles = input.context.roles;
    const scope = input.context.relevantFiles || [];
    const memory = input.context.memoryContext || {};

    const sections: string[] = [];

    // Header
    sections.push(`# Magneto AI Task: ${task.title || 'Untitled'}\n`);
    sections.push(`> Auto-generated by Magneto Telepathy. Execute this task.\n`);

    // Task details
    sections.push(`## Task\n`);
    sections.push(`- **Title:** ${task.title || 'Untitled'}`);
    sections.push(`- **Type:** ${task.type || input.context.classification || 'general'}`);
    sections.push(`- **Description:** ${task.description || 'N/A'}`);
    if (task.priority) sections.push(`- **Priority:** ${task.priority}`);
    sections.push('');

    // Roles
    sections.push(`## Assigned Roles\n`);
    for (const role of roles) {
      sections.push(`- **${role}** — Act as this role when implementing`);
    }
    sections.push('');

    // Scoped files
    if (scope.length > 0) {
      sections.push(`## Scoped Files (only modify these)\n`);
      sections.push('```');
      for (const file of scope) {
        sections.push(file);
      }
      sections.push('```');
      sections.push('');
    }

    // Memory context
    if (memory && Object.keys(memory).length > 0) {
      sections.push(`## Project Memory\n`);
      if (memory.decisions) {
        sections.push(`### Previous Decisions`);
        sections.push(String(memory.decisions));
        sections.push('');
      }
      if (memory.patterns) {
        sections.push(`### Patterns`);
        sections.push(String(memory.patterns));
        sections.push('');
      }
    }

    // Security constraints
    sections.push(`## Security Constraints\n`);
    sections.push(`- **Risk Level:** ${input.security.securityRisk}`);
    sections.push(`- **Execution Mode:** ${input.mode}`);
    sections.push(`- **Approval Required:** ${input.security.approvalRequired}`);
    const protectedPaths = (input.security as any).blockedPaths || [];
    if (protectedPaths.length > 0) {
      sections.push(`- **Protected Paths:** ${protectedPaths.join(', ')}`);
    }
    sections.push('');

    // Instructions
    sections.push(`## Instructions\n`);
    sections.push(`1. Read the task description above carefully`);
    sections.push(`2. Act in the assigned roles: ${roles.join(', ')}`);
    sections.push(`3. Only modify files in the scoped paths listed above`);
    sections.push(`4. Follow security constraints — do not touch protected paths`);
    sections.push(`5. Implement the changes, write tests if tester role is assigned`);
    sections.push(`6. Provide a summary of changes when complete`);
    sections.push('');

    return sections.join('\n');
  }

  private buildWorkflow(input: RunnerInput, prompt: string): string {
    const taskId = (input.task.id as string) || 'task';
    return `---
description: Magneto task ${taskId} - ${input.task.title || 'Execute task'}
---

${prompt}
`;
  }
}
