/**
 * Gemini Runner
 * 
 * Generates prompts for Google Gemini and writes to .magneto/cache/ for handoff.
 * If GEMINI_API_KEY is set, can also make direct API calls.
 */

import * as fs from 'fs';
import * as path from 'path';
import { Runner, RunnerInput, RunnerOutput } from './types';
import { logger } from '../utils/logger';

export class GeminiRunner implements Runner {
  name = 'Gemini Runner';
  type = 'gemini' as const;

  async execute(input: RunnerInput): Promise<RunnerOutput> {
    logger.info('✨ Executing task via Gemini handoff...');

    const prompt = this.buildPrompt(input);
    const taskId = (input.task.id as string) || 'task';
    const cachePath = path.join(input.projectRoot, '.magneto', 'cache', `prompt-${taskId}.md`);

    fs.mkdirSync(path.dirname(cachePath), { recursive: true });
    fs.writeFileSync(cachePath, prompt, 'utf-8');

    logger.success(`Gemini prompt ready: ${cachePath}`);

    return {
      success: true,
      findings: [{
        source: 'gemini',
        content: `Task prompt written to ${cachePath}. Gemini will execute.`,
        confidence: 0.9,
      }],
      risks: [],
      rawOutput: prompt,
      promptPath: cachePath,
      metadata: { runner: 'gemini', promptPath: cachePath, handedOff: true },
    };
  }

  private buildPrompt(input: RunnerInput): string {
    const task = input.task;
    const roles = input.context.roles;

    return `# Magneto AI Task: ${task.title || 'Untitled'}

> Auto-generated by Magneto Telepathy for Gemini.

## Task
- **Title:** ${task.title || 'Untitled'}
- **Type:** ${task.type || input.context.classification || 'general'}
- **Description:** ${task.description || 'N/A'}

## Roles
${roles.map(r => `- ${r}`).join('\n')}

## Security
- **Risk:** ${input.security.securityRisk}
- **Mode:** ${input.mode}

## Instructions
Execute this task following Magneto AI conventions. Read .magneto/ for context.
`;
  }
}
