import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';
import * as os from 'os';
import { logger } from '../utils/logger';

/**
 * Zero-Trust Memory Lock System
 * ─────────────────────────────
 * Goals:
 *  1. Memory cannot be modified while a task is running (runtime lock)
 *  2. Memory writes require explicit unlock + ownership check
 *  3. Every memory file is hashed; tampering is detected on every read
 *  4. memory.lock is the single source of truth for what's authorised
 *  5. Only owners (or root) can modify the lock itself
 *
 * Files involved:
 *  .magneto/memory/memory.lock        — SHA-256 manifest + lock state
 *  .magneto/memory/memory.lock.sig    — HMAC signature of the manifest
 *  .magneto/state/runtime.lock        — sentinel; present while a task is running
 */

export type LockMode = 'locked' | 'unlocked';

export interface LockedFileEntry {
  path: string;        // relative to memory dir
  sha256: string;      // hex digest of contents at lock time
  size: number;
  modifiedAt: string;  // ISO timestamp
  permissions: string; // octal as string e.g. "0400"
}

export interface MemoryLockManifest {
  version: 1;
  mode: LockMode;
  lockedAt: string;
  lockedBy: {
    uid: number;
    user: string;
    hostname: string;
  };
  hmacAlgorithm: 'sha256';
  files: LockedFileEntry[];
  policy: {
    allowRuntimeWrites: false;        // hard-coded false — never allowed
    requireOwnerToUnlock: boolean;
    requireRootToUnlock: boolean;
    rejectOnHashMismatch: boolean;
  };
}

const LOCK_FILENAME = 'memory.lock';
const SIG_FILENAME = 'memory.lock.sig';
const RUNTIME_LOCK = path.join('state', 'runtime.lock');

// ─── Path helpers ────────────────────────────────────────────────────────

export function memoryDir(projectRoot: string): string {
  return path.join(projectRoot, '.magneto', 'memory');
}

export function lockFilePath(projectRoot: string): string {
  return path.join(memoryDir(projectRoot), LOCK_FILENAME);
}

export function sigFilePath(projectRoot: string): string {
  return path.join(memoryDir(projectRoot), SIG_FILENAME);
}

export function runtimeLockPath(projectRoot: string): string {
  return path.join(projectRoot, '.magneto', RUNTIME_LOCK);
}

// ─── Hashing & signing ───────────────────────────────────────────────────

function sha256File(filePath: string): string {
  const buf = fs.readFileSync(filePath);
  return crypto.createHash('sha256').update(buf).digest('hex');
}

function sha256Buffer(buf: Buffer): string {
  return crypto.createHash('sha256').update(buf).digest('hex');
}

/**
 * Derive an HMAC key from machine-bound material so the signature can't be
 * trivially regenerated by a different process or host.
 *  - hostname + uid + ~/.magneto-key (created on first lock with 0400 perms)
 */
function deriveKey(): Buffer {
  const homeKeyPath = path.join(os.homedir(), '.magneto-key');
  if (!fs.existsSync(homeKeyPath)) {
    const seed = crypto.randomBytes(32);
    fs.writeFileSync(homeKeyPath, seed);
    try { fs.chmodSync(homeKeyPath, 0o400); } catch { /* windows */ }
  }
  const keyMaterial = fs.readFileSync(homeKeyPath);
  const salt = `${os.hostname()}:${process.getuid?.() ?? 'unknown'}`;
  return crypto.createHmac('sha256', keyMaterial).update(salt).digest();
}

function signManifest(manifest: MemoryLockManifest): string {
  const json = JSON.stringify(manifest);
  return crypto.createHmac('sha256', deriveKey()).update(json).digest('hex');
}

function verifySignature(manifest: MemoryLockManifest, signature: string): boolean {
  const expected = signManifest(manifest);
  // constant-time compare
  if (expected.length !== signature.length) return false;
  return crypto.timingSafeEqual(Buffer.from(expected, 'hex'), Buffer.from(signature, 'hex'));
}

// ─── File enumeration ────────────────────────────────────────────────────

function listMemoryFiles(memDir: string): string[] {
  const files: string[] = [];
  if (!fs.existsSync(memDir)) return files;

  const walk = (dir: string) => {
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch { return; }
    for (const entry of entries) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(full);
      } else if (entry.name !== LOCK_FILENAME && entry.name !== SIG_FILENAME) {
        files.push(full);
      }
    }
  };
  walk(memDir);
  return files;
}

// ─── Lock / unlock / verify ──────────────────────────────────────────────

export interface LockOptions {
  requireRootToUnlock?: boolean;
  requireOwnerToUnlock?: boolean;
  rejectOnHashMismatch?: boolean;
}

export function lockMemory(projectRoot: string, options: LockOptions = {}): MemoryLockManifest {
  const memDir = memoryDir(projectRoot);
  if (!fs.existsSync(memDir)) {
    fs.mkdirSync(memDir, { recursive: true });
  }

  // Refuse to lock while a task is running — would deadlock the runtime
  if (isRuntimeActive(projectRoot)) {
    throw new Error('Cannot lock memory while a task is running. Wait for completion or stop the task first.');
  }

  const allFiles = listMemoryFiles(memDir);
  const entries: LockedFileEntry[] = allFiles.map((full) => {
    const stat = fs.statSync(full);
    const rel = path.relative(memDir, full).replace(/\\/g, '/');
    return {
      path: rel,
      sha256: sha256File(full),
      size: stat.size,
      modifiedAt: stat.mtime.toISOString(),
      permissions: '0' + (stat.mode & 0o777).toString(8).padStart(3, '0'),
    };
  });

  const manifest: MemoryLockManifest = {
    version: 1,
    mode: 'locked',
    lockedAt: new Date().toISOString(),
    lockedBy: {
      uid: process.getuid?.() ?? -1,
      user: os.userInfo().username,
      hostname: os.hostname(),
    },
    hmacAlgorithm: 'sha256',
    files: entries,
    policy: {
      allowRuntimeWrites: false,
      requireOwnerToUnlock: options.requireOwnerToUnlock ?? true,
      requireRootToUnlock: options.requireRootToUnlock ?? false,
      rejectOnHashMismatch: options.rejectOnHashMismatch ?? true,
    },
  };

  // Set the actual files to read-only on disk
  for (const file of allFiles) {
    try { fs.chmodSync(file, 0o400); } catch { /* windows */ }
  }

  // Write the manifest then the signature
  fs.writeFileSync(lockFilePath(projectRoot), JSON.stringify(manifest, null, 2), 'utf-8');
  const sig = signManifest(manifest);
  fs.writeFileSync(sigFilePath(projectRoot), sig, 'utf-8');

  // Lock the lock files themselves
  try {
    fs.chmodSync(lockFilePath(projectRoot), 0o400);
    fs.chmodSync(sigFilePath(projectRoot), 0o400);
  } catch { /* windows */ }

  logger.info(`[zero-trust] 🔒 Memory locked — ${entries.length} files hashed and signed`);
  return manifest;
}

export interface UnlockOptions {
  force?: boolean;   // skip hash verification
}

export function unlockMemory(projectRoot: string, options: UnlockOptions = {}): MemoryLockManifest {
  const lockPath = lockFilePath(projectRoot);
  const sigPath = sigFilePath(projectRoot);

  if (!fs.existsSync(lockPath)) {
    throw new Error('Memory is not locked. No memory.lock file found.');
  }

  // Refuse to unlock while a task is running
  if (isRuntimeActive(projectRoot)) {
    throw new Error('Cannot unlock memory while a task is running. Memory updates only allowed in offline mode.');
  }

  const manifest = readManifest(projectRoot);

  // Ownership / root checks
  const currentUid = process.getuid?.() ?? -1;
  if (manifest.policy.requireRootToUnlock && currentUid !== 0) {
    throw new Error('Memory unlock requires root (uid 0). Current uid: ' + currentUid);
  }
  if (manifest.policy.requireOwnerToUnlock && currentUid !== manifest.lockedBy.uid && currentUid !== 0) {
    throw new Error(`Memory unlock requires the locking user (uid ${manifest.lockedBy.uid}). Current uid: ${currentUid}`);
  }

  // Verify signature
  const sig = fs.readFileSync(sigPath, 'utf-8').trim();
  if (!verifySignature(manifest, sig)) {
    throw new Error('Memory lock signature INVALID — manifest has been tampered with. Refusing to unlock.');
  }

  // Optionally verify each file's hash
  if (!options.force && manifest.policy.rejectOnHashMismatch) {
    const memDir = memoryDir(projectRoot);
    const tampered: string[] = [];
    for (const entry of manifest.files) {
      const full = path.join(memDir, entry.path);
      if (!fs.existsSync(full)) {
        tampered.push(`${entry.path} (deleted)`);
        continue;
      }
      const actual = sha256File(full);
      if (actual !== entry.sha256) tampered.push(`${entry.path} (hash mismatch)`);
    }
    if (tampered.length > 0) {
      throw new Error(`Memory tampering detected:\n  ${tampered.join('\n  ')}\nUse --force to unlock anyway.`);
    }
  }

  // Restore writable permissions
  const memDir = memoryDir(projectRoot);
  for (const entry of manifest.files) {
    const full = path.join(memDir, entry.path);
    try { if (fs.existsSync(full)) fs.chmodSync(full, 0o600); } catch { /* windows */ }
  }
  try {
    fs.chmodSync(lockPath, 0o600);
    fs.chmodSync(sigPath, 0o600);
  } catch { /* windows */ }

  // Update manifest mode + rewrite (still signed) so 'is locked' returns false
  const unlocked: MemoryLockManifest = { ...manifest, mode: 'unlocked' };
  fs.writeFileSync(lockPath, JSON.stringify(unlocked, null, 2), 'utf-8');
  fs.writeFileSync(sigPath, signManifest(unlocked), 'utf-8');

  logger.info('[zero-trust] 🔓 Memory unlocked — writes now permitted');
  return unlocked;
}

export interface VerifyResult {
  signatureValid: boolean;
  fileHashesValid: boolean;
  totalFiles: number;
  tamperedFiles: string[];
  missingFiles: string[];
  unrecordedFiles: string[];
}

export function verifyMemory(projectRoot: string): VerifyResult {
  const lockPath = lockFilePath(projectRoot);
  if (!fs.existsSync(lockPath)) {
    throw new Error('Memory is not locked. Run `magneto memory lock` first.');
  }

  const manifest = readManifest(projectRoot);
  const sigPath = sigFilePath(projectRoot);
  const sig = fs.existsSync(sigPath) ? fs.readFileSync(sigPath, 'utf-8').trim() : '';
  const signatureValid = sig.length > 0 && verifySignature(manifest, sig);

  const memDir = memoryDir(projectRoot);
  const tamperedFiles: string[] = [];
  const missingFiles: string[] = [];
  const recorded = new Set(manifest.files.map((f) => f.path));

  for (const entry of manifest.files) {
    const full = path.join(memDir, entry.path);
    if (!fs.existsSync(full)) {
      missingFiles.push(entry.path);
      continue;
    }
    if (sha256File(full) !== entry.sha256) tamperedFiles.push(entry.path);
  }

  // Detect new files not in manifest (potential injection)
  const onDisk = listMemoryFiles(memDir).map((f) => path.relative(memDir, f).replace(/\\/g, '/'));
  const unrecordedFiles = onDisk.filter((p) => !recorded.has(p));

  return {
    signatureValid,
    fileHashesValid: tamperedFiles.length === 0 && missingFiles.length === 0,
    totalFiles: manifest.files.length,
    tamperedFiles,
    missingFiles,
    unrecordedFiles,
  };
}

export function readManifest(projectRoot: string): MemoryLockManifest {
  const lockPath = lockFilePath(projectRoot);
  const raw = fs.readFileSync(lockPath, 'utf-8');
  return JSON.parse(raw) as MemoryLockManifest;
}

export function isMemoryLocked(projectRoot: string): boolean {
  const lockPath = lockFilePath(projectRoot);
  if (!fs.existsSync(lockPath)) return false;
  try {
    const manifest = readManifest(projectRoot);
    return manifest.mode === 'locked';
  } catch {
    return false;
  }
}

// ─── Runtime gating ──────────────────────────────────────────────────────

export function markRuntimeActive(projectRoot: string, taskId: string): void {
  const lockFile = runtimeLockPath(projectRoot);
  fs.mkdirSync(path.dirname(lockFile), { recursive: true });
  const data = {
    taskId,
    pid: process.pid,
    startedAt: new Date().toISOString(),
  };
  fs.writeFileSync(lockFile, JSON.stringify(data, null, 2), 'utf-8');
}

export function clearRuntimeActive(projectRoot: string): void {
  const lockFile = runtimeLockPath(projectRoot);
  if (fs.existsSync(lockFile)) fs.unlinkSync(lockFile);
}

export function isRuntimeActive(projectRoot: string): boolean {
  const lockFile = runtimeLockPath(projectRoot);
  if (!fs.existsSync(lockFile)) return false;
  try {
    const data = JSON.parse(fs.readFileSync(lockFile, 'utf-8'));
    // Stale lock detection: if pid no longer exists, treat as inactive
    if (typeof data.pid === 'number') {
      try {
        process.kill(data.pid, 0);
        return true;          // pid alive → runtime active
      } catch {
        return false;          // pid gone → stale lock
      }
    }
    return true;
  } catch {
    return false;
  }
}

// ─── Write enforcement ───────────────────────────────────────────────────

/**
 * Asserts that a memory write is currently permitted.
 * Call this before ANY write into .magneto/memory/.
 *
 * Throws if:
 *   - memory is locked, OR
 *   - a task is currently running (runtime.lock present)
 */
export function assertMemoryWritable(projectRoot: string): void {
  if (isRuntimeActive(projectRoot)) {
    throw new Error(
      '[zero-trust] Memory is read-only while a task is running. ' +
      'Stop the task before modifying memory, or wait for it to finish.'
    );
  }

  if (isMemoryLocked(projectRoot)) {
    throw new Error(
      '[zero-trust] Memory is locked. Run `magneto memory unlock` first ' +
      '(requires owner; root may also be required by policy).'
    );
  }
}

/**
 * Computes the hash of a piece of content that's about to be written.
 * Returned hash should be recorded in the manifest by lockMemory().
 */
export function hashContent(content: string | Buffer): string {
  const buf = typeof content === 'string' ? Buffer.from(content, 'utf-8') : content;
  return sha256Buffer(buf);
}
