// Shared "constitution" template. Used by every adapter so that all three
// frameworks ship with the same baseline rules — the article calls out that
// single-line "don't do X" rules get ignored by LLMs; we always pair with
// "because Y, instead do Z".
//
// References:
//   - github/spec-kit#980 — separation of WHAT/WHY (spec) from HOW (plan)
//   - EPAM Spec Kit brownfield case study — try-catch override failure
//   - arXiv 2602.00180v1 §5 (constitution rule efficacy)

export interface ConstitutionTemplateOptions {
  projectName: string;
  framework: 'openspec' | 'speckit' | 'bmad';
}

export function renderConstitution(opts: ConstitutionTemplateOptions): string {
  const { projectName, framework } = opts;
  return `# ${projectName} — Project Constitution

> Generated by Magneto SDD (${framework}).
> Edit this file. Every spec and plan in this repo MUST defer to it.

## How to read this file

Each rule states **WHY** before **WHAT** before **HOW**. LLMs ignore terse
prohibitions; they follow rules that explain the reason. If you add a rule,
keep that pattern.

---

## 1. Testing

**Why:** Untested code rotates into bug-debt the moment the next agent edits it.
**Rule:** Every change ships with at least one regression test in the same PR.
**How:** Use the existing test runner (\`npm test\` / \`pytest\` / \`go test ./...\`).
Tests live next to source under \`tests/\` mirroring the package path.

## 2. Error handling

**Why:** Inconsistent error handling makes incident response slow and turns
edge cases into outages.
**Rule:** Do NOT add try/catch in route handlers, controllers, or CLI entry
points. Use centralized middleware / global error handlers instead.
**How:** Throw typed errors from business logic; let the framework's error
middleware translate them to HTTP / CLI exit codes. Log once, at the boundary.

## 3. Security posture

**Why:** Hardcoded secrets, weak crypto, and unsandboxed shell execution are
the top three causes of post-merge incidents.
**Rule:** Never commit credentials. Never use MD5/SHA1 for security-relevant
hashing. Never invoke a shell with user-controlled input.
**How:** Use environment variables + \`magneto security audit\`. Use SHA-256
or argon2id. Pass argv arrays to \`spawn\`, never strings to \`exec\`.

## 4. Specification discipline (this is the SDD core)

**Why:** Specs that diverge from code mislead the next agent worse than no
spec at all (Wattenberger, 2025; InfoQ 2026).
**Rule:** When implementation diverges from spec, update the spec in the same
commit. Run \`magneto sdd sync\` before merge.
**How:**
  - **spec.md** = WHAT and WHY (technology-agnostic).
  - **plan.md / design.md** = HOW (stack, libraries, file layout).
  - **tasks.md** = ordered, testable units, each one PR-sized.

## 5. Stack & dependencies

**Why:** Stack drift fragments tooling, multiplies CI cost, and confuses
agents that pattern-match the wrong ecosystem.
**Rule:** New runtime dependencies require a one-line justification in the
spec's "design.md" under "Dependency choices".
**How:** Prefer the language's standard library. When you must add a
package, pin a major version and run \`magneto security scan-deps\`.

## 6. Non-goals (read this before each change)

**Why:** "Non-goals" stops the agent from gold-plating and prevents scope
creep — the #2 SDD failure mode after drift.
**Rule:** Every spec.md MUST contain a "Non-goals" section listing at least
3 things this change deliberately does not do.

---

## Project-specific rules

<!-- Add your team's specific rules below. Keep the WHY/WHAT/HOW pattern. -->

`;
}
